spring:

  datasource1:
    url: jdbc:h2:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 3


  datasource2:
    url: jdbc:h2:~/test2
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      initialization-fail-timeout: 1000000 # Member 서버가 기동시간을 기다리기 위해 설정
      maximum-pool-size: 20
      minimum-idle: 6

h2:
  console:
    enable: true
    path: /h2-console

  jpa:

    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: H2


logging:
  level:
    com.zaxxer.hikari: TRACE
    com.zaxxer.hikari.HikariConfig: DEBUG
